/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0/samples
 */
plugins {
    base
    java
    kotlin("jvm") version "1.5.21"
}

val javaVersion = JavaVersion.VERSION_16

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        this.jvmTarget = javaVersion.toString()
    }
}

java {
    toolchain {
        this.languageVersion.set(JavaLanguageVersion.of(javaVersion.toString()))
    }
}
