/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0/samples
 */
plugins {
    base
    java
    kotlin("jvm") version "1.5.21"
}

val javaVersion = JavaVersion.VERSION_16

repositories {
    mavenCentral()
}

dependencies {
    api(platform("org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.5.1"))
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()

    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        this.jvmTarget = javaVersion.toString()
        this.freeCompilerArgs = listOf("-Xopt-in=kotlin.RequiresOptIn")
    }
}

java {
    toolchain {
        this.languageVersion.set(JavaLanguageVersion.of(javaVersion.toString()))
    }
}
